# -*- coding: utf-8 -*-
"""Labworks1.python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pbLt0DUV9Qcm6i1i7BDtqlWjCxVfqvm
"""

# Exercise 1
r = float(input("Enter circle radius? "))
area = 3.14 * r * r
print("Circle area =", area)

# Exercise 2
c = float(input("Enter the temperature in Celsius? "))
f = c * 9 / 5 + 32
print(c, "(C) =", f, "(F)")

# Exercise 3
n = int(input("Enter a number? "))
is_prime = True
if n < 2:
    is_prime = False
else:
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            is_prime = False
            break
if is_prime:
    print(n, "is a prime number")
else:
    print(n, "is a NOT prime number")

# Exercise 4
n = int(input("Enter a number? "))
total = 0
for i in range(1, n):
    if n % i == 0:
        total += i
if n > 0 and total == n:
    print(n, "is a perfect number")
else:
    print(n, "is a NOT perfect number")

# Exercise 5
colors_listed = ["Blue", "Yellow", "Purple", "Red", "Orange"]
input_color = input("What is your favorite color? ")
if input_color in colors_listed:
    print("Your color is at index", colors_listed.index(input_color), "in my list")
else:
    print("Sorry, I could not find your color")

# Exercise 6
range1 = range(0, 7)        # 0, 1, 2, 3, 4, 5, 6
range2 = range(1, 11, 3)    # 1, 4, 7, 10
range3 = range(5, 0, -1)    # 5, 4, 3, 2, 1
range4 = range(6, -3, -2)   # 6, 4, 2, 0, -2
print("range1:", list(range1))
print("range2:", list(range2))
print("range3:", list(range3))
print("range4:", list(range4))

# Exercise 7
def remove_dollar_sign(s):
    new_s = ""
    for charac in s:
        if charac != "$":
            new_s += charac
    return new_s
if __name__ == "__main__":
    print(remove_dollar_sign("12$ and 34$"))

# Exercise 8
def extract_even(l):
    result = []
    for x in l:
        if x % 2 == 0:
            result.append(x)
    return result
if __name__ == "__main__":
    print(extract_even([1, 4, 5, -1, 10]))

# Exercise 9
def factorial(n):
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result
if __name__ == "__main__":
    print(factorial(0))
    print(factorial(5))

# Exercise 10
def get_divisors(n):
    divisors = []
    for i in range(1, n + 1):
        if n % i == 0:
            divisors.append(i)
    return divisors
if __name__ == "__main__":
    print(get_divisors(12))

# Exercise 11
x1 = float(input("x1? "))
y1 = float(input("y1? "))
x2 = float(input("x2? "))
y2 = float(input("y2? "))
d = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5
print("Distance =", d)

# Exercise 12
def pattern(m, n):
    for i in range(m):
        for j in range(n):
            if i == 0 or i == m - 1 or j == 0 or j == n - 1:
                print("*", end=" ")
            else:
                print(" ", end=" ")
        print()
if __name__ == "__main__":
    pattern(4, 5)